# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 'Big O Theory Club'
description: 'Thoughts on theoretical computer science and research life.'
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://theoryclub.github.io' # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Defaults
defaults:
    -
        scope:
            path: ''
            type: 'posts'
        values:
            layout: post
            includecss: post.css
            moreexists: true
            permalink: /:year/:title
            author: Theory Club
